name: CI

on: 
  push: 
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  Build-and-Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
      - run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Xcode version
      - run: /usr/bin/xcodebuild -version

      - name: Install dependencies
      - run: pod install --repo-update

      - name: Build
      - run: xcodebuild clean build -scheme reddit-chile -worspace reddit-chile.xcworkspace -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro Max' | xcpretty && exit ${PIPESTATUS[0]}
