language:
  - swift
osx_image: xcode13.1
before_install:
- gem install cocoapods # Since Travis is not always on latest version
# Avoid error: Encountered an unknown error (uninitialized constant Concurrent::Promises) during validation
# https://github.com/CocoaPods/CocoaPods/issues/8948
- gem update concurrent-ruby
- pod install
# - pod install --project-directory=Example
script:
  - xcodebuild -scheme reddit-chile -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
