language:
  - swift
osx_image: xcode13.2
before_install:
- gem install cocoapods # Since Travis is not always on latest version
# Avoid error: Encountered an unknown error (uninitialized constant Concurrent::Promises) during validation
# https://github.com/CocoaPods/CocoaPods/issues/8948
- gem update concurrent-ruby
- pod install --repo-update
# - pod install --project-directory=Example
script:
    - xcodebuild clean build test -scheme reddit-chile -workspace reddit-chile.xcworkspace -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro Max' | xcpretty && exit ${PIPESTATUS[0]}
after_success:
  - bash <(curl -s https://codecov.io/bash)
